import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';
import SiteLayout from '@/components/layouts/SiteLayout';
import { routing } from '@/i18n/routing';
// import '../../globals.css';

export const metadata: Metadata = {
  title: 'Red Blog',
  description: 'Generated by create next app',
};

export default async function LocaleLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning={true}>
      {/* Font from utils/font you can modify font in that file and add font variable in tailwind.config */}
      <body suppressHydrationWarning={true}>
        <SiteLayout>
          <NextIntlClientProvider messages={messages}>{children}</NextIntlClientProvider>
        </SiteLayout>
      </body>
    </html>
  );
}
