import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';
import { SessionProvider } from 'next-auth/react';

import SiteLayout from '@/components/layouts/SiteLayout';
import { redirect, routing } from '@/i18n/routing';
import { auth } from '@/lib/auth';

export const metadata: Metadata = {
  title: 'Boilerplate',
  description: 'Generated by create next app',
};

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const session = await auth();

  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  console.log('session?.user => ', session?.user);

  if (!session?.user)
    return redirect({
      href: {
        pathname: '/login',
        query: undefined,
      },
      locale,
    });

  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning={true}>
      {/* Font from utils/font you can modify font in that file and add font variable in tailwind.config */}
      <body suppressHydrationWarning={true}>
        <SiteLayout>
          <NextIntlClientProvider messages={messages}>
            <SessionProvider>{children}</SessionProvider>
          </NextIntlClientProvider>
        </SiteLayout>
      </body>
    </html>
  );
}
